/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayPostRouteImport } from './routes/play/post'
import { Route as PlayParkRouteImport } from './routes/play/park'
import { Route as PlayLibraryRouteImport } from './routes/play/library'
import { Route as PlayHqRouteImport } from './routes/play/hq'
import { Route as PlayFortRouteImport } from './routes/play/fort'
import { Route as PlayBridgeRouteImport } from './routes/play/bridge'
import { Route as PlayBankRouteImport } from './routes/play/bank'
import { Route as PlayArcadeRouteImport } from './routes/play/arcade'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPostRoute = PlayPostRouteImport.update({
  id: '/play/post',
  path: '/play/post',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayParkRoute = PlayParkRouteImport.update({
  id: '/play/park',
  path: '/play/park',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayLibraryRoute = PlayLibraryRouteImport.update({
  id: '/play/library',
  path: '/play/library',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayHqRoute = PlayHqRouteImport.update({
  id: '/play/hq',
  path: '/play/hq',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFortRoute = PlayFortRouteImport.update({
  id: '/play/fort',
  path: '/play/fort',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBridgeRoute = PlayBridgeRouteImport.update({
  id: '/play/bridge',
  path: '/play/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayBankRoute = PlayBankRouteImport.update({
  id: '/play/bank',
  path: '/play/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayArcadeRoute = PlayArcadeRouteImport.update({
  id: '/play/arcade',
  path: '/play/arcade',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/play/arcade': typeof PlayArcadeRoute
  '/play/bank': typeof PlayBankRoute
  '/play/bridge': typeof PlayBridgeRoute
  '/play/fort': typeof PlayFortRoute
  '/play/hq': typeof PlayHqRoute
  '/play/library': typeof PlayLibraryRoute
  '/play/park': typeof PlayParkRoute
  '/play/post': typeof PlayPostRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/play/arcade': typeof PlayArcadeRoute
  '/play/bank': typeof PlayBankRoute
  '/play/bridge': typeof PlayBridgeRoute
  '/play/fort': typeof PlayFortRoute
  '/play/hq': typeof PlayHqRoute
  '/play/library': typeof PlayLibraryRoute
  '/play/park': typeof PlayParkRoute
  '/play/post': typeof PlayPostRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/play/arcade': typeof PlayArcadeRoute
  '/play/bank': typeof PlayBankRoute
  '/play/bridge': typeof PlayBridgeRoute
  '/play/fort': typeof PlayFortRoute
  '/play/hq': typeof PlayHqRoute
  '/play/library': typeof PlayLibraryRoute
  '/play/park': typeof PlayParkRoute
  '/play/post': typeof PlayPostRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/play/arcade'
    | '/play/bank'
    | '/play/bridge'
    | '/play/fort'
    | '/play/hq'
    | '/play/library'
    | '/play/park'
    | '/play/post'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/play/arcade'
    | '/play/bank'
    | '/play/bridge'
    | '/play/fort'
    | '/play/hq'
    | '/play/library'
    | '/play/park'
    | '/play/post'
  id:
    | '__root__'
    | '/'
    | '/play/arcade'
    | '/play/bank'
    | '/play/bridge'
    | '/play/fort'
    | '/play/hq'
    | '/play/library'
    | '/play/park'
    | '/play/post'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayArcadeRoute: typeof PlayArcadeRoute
  PlayBankRoute: typeof PlayBankRoute
  PlayBridgeRoute: typeof PlayBridgeRoute
  PlayFortRoute: typeof PlayFortRoute
  PlayHqRoute: typeof PlayHqRoute
  PlayLibraryRoute: typeof PlayLibraryRoute
  PlayParkRoute: typeof PlayParkRoute
  PlayPostRoute: typeof PlayPostRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/post': {
      id: '/play/post'
      path: '/play/post'
      fullPath: '/play/post'
      preLoaderRoute: typeof PlayPostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/park': {
      id: '/play/park'
      path: '/play/park'
      fullPath: '/play/park'
      preLoaderRoute: typeof PlayParkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/library': {
      id: '/play/library'
      path: '/play/library'
      fullPath: '/play/library'
      preLoaderRoute: typeof PlayLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/hq': {
      id: '/play/hq'
      path: '/play/hq'
      fullPath: '/play/hq'
      preLoaderRoute: typeof PlayHqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/fort': {
      id: '/play/fort'
      path: '/play/fort'
      fullPath: '/play/fort'
      preLoaderRoute: typeof PlayFortRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/bridge': {
      id: '/play/bridge'
      path: '/play/bridge'
      fullPath: '/play/bridge'
      preLoaderRoute: typeof PlayBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/bank': {
      id: '/play/bank'
      path: '/play/bank'
      fullPath: '/play/bank'
      preLoaderRoute: typeof PlayBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/arcade': {
      id: '/play/arcade'
      path: '/play/arcade'
      fullPath: '/play/arcade'
      preLoaderRoute: typeof PlayArcadeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayArcadeRoute: PlayArcadeRoute,
  PlayBankRoute: PlayBankRoute,
  PlayBridgeRoute: PlayBridgeRoute,
  PlayFortRoute: PlayFortRoute,
  PlayHqRoute: PlayHqRoute,
  PlayLibraryRoute: PlayLibraryRoute,
  PlayParkRoute: PlayParkRoute,
  PlayPostRoute: PlayPostRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
